// Vocabulaire anglais, même structure que vocabEs.js (mêmes id/level/topic/fr) pour rester
// alignés sur la même échelle de niveaux. Pas de distinction de variante (UK/US) pour l'instant.
export const VOCAB = [
  // Niveau 1 — Salutations
  { id: 'v1', level: 1, topic: 'Salutations', en: 'hello', fr: 'salut / bonjour' },
  { id: 'v2', level: 1, topic: 'Salutations', en: 'good morning', fr: 'bonjour (le matin)' },
  { id: 'v3', level: 1, topic: 'Salutations', en: 'good evening', fr: 'bonsoir / bonne nuit' },
  { id: 'v4', level: 1, topic: 'Salutations', en: 'thank you', fr: 'merci' },
  { id: 'v5', level: 1, topic: 'Salutations', en: 'please', fr: 's’il te/vous plaît' },
  { id: 'v6', level: 1, topic: 'Salutations', en: 'goodbye', fr: 'au revoir' },
  { id: 'v49', level: 1, topic: 'Salutations', en: 'good afternoon', fr: 'bon après-midi' },
  { id: 'v50', level: 1, topic: 'Salutations', en: 'see you later', fr: 'à plus tard' },
  { id: 'v51', level: 1, topic: 'Salutations', en: 'you’re welcome', fr: 'de rien' },
  { id: 'v52', level: 1, topic: 'Salutations', en: 'excuse me', fr: 'excusez-moi' },
  { id: 'v53', level: 1, topic: 'Salutations', en: 'I’m sorry', fr: 'je suis désolé' },
  { id: 'v54', level: 1, topic: 'Salutations', en: 'welcome', fr: 'bienvenue' },
  { id: 'v55', level: 1, topic: 'Salutations', en: 'how’s it going?', fr: 'comment ça va ? (familier)' },
  { id: 'v56', level: 1, topic: 'Salutations', en: 'nice to meet you', fr: 'enchanté' },
  { id: 'v57', level: 1, topic: 'Salutations', en: 'enjoy your meal', fr: 'bon appétit' },

  // Niveau 2 — Bases
  { id: 'v7', level: 2, topic: 'Bases', en: 'one', fr: 'un' },
  { id: 'v8', level: 2, topic: 'Bases', en: 'two', fr: 'deux' },
  { id: 'v9', level: 2, topic: 'Bases', en: 'three', fr: 'trois' },
  { id: 'v10', level: 2, topic: 'Bases', en: 'yes', fr: 'oui' },
  { id: 'v11', level: 2, topic: 'Bases', en: 'no', fr: 'non' },
  { id: 'v12', level: 2, topic: 'Bases', en: 'how are you?', fr: 'comment vas-tu ?' },
  { id: 'v58', level: 2, topic: 'Bases', en: 'four', fr: 'quatre' },
  { id: 'v59', level: 2, topic: 'Bases', en: 'five', fr: 'cinq' },
  { id: 'v60', level: 2, topic: 'Bases', en: 'six', fr: 'six' },
  { id: 'v61', level: 2, topic: 'Bases', en: 'seven', fr: 'sept' },
  { id: 'v62', level: 2, topic: 'Bases', en: 'eight', fr: 'huit' },
  { id: 'v63', level: 2, topic: 'Bases', en: 'nine', fr: 'neuf' },
  { id: 'v64', level: 2, topic: 'Bases', en: 'ten', fr: 'dix' },
  { id: 'v65', level: 2, topic: 'Bases', en: 'also', fr: 'aussi' },
  { id: 'v66', level: 2, topic: 'Bases', en: 'now', fr: 'maintenant' },

  // Niveau 3 — Famille
  { id: 'v13', level: 3, topic: 'Famille', en: 'mother', fr: 'mère' },
  { id: 'v14', level: 3, topic: 'Famille', en: 'father', fr: 'père' },
  { id: 'v15', level: 3, topic: 'Famille', en: 'sister', fr: 'sœur' },
  { id: 'v16', level: 3, topic: 'Famille', en: 'brother', fr: 'frère' },
  { id: 'v17', level: 3, topic: 'Famille', en: 'friend', fr: 'ami' },
  { id: 'v67', level: 3, topic: 'Famille', en: 'son', fr: 'fils' },
  { id: 'v68', level: 3, topic: 'Famille', en: 'daughter', fr: 'fille' },
  { id: 'v69', level: 3, topic: 'Famille', en: 'grandfather', fr: 'grand-père' },
  { id: 'v70', level: 3, topic: 'Famille', en: 'grandmother', fr: 'grand-mère' },
  { id: 'v71', level: 3, topic: 'Famille', en: 'uncle', fr: 'oncle' },
  { id: 'v72', level: 3, topic: 'Famille', en: 'aunt', fr: 'tante' },
  { id: 'v73', level: 3, topic: 'Famille', en: 'cousin', fr: 'cousin' },
  { id: 'v74', level: 3, topic: 'Famille', en: 'child (boy)', fr: 'enfant (garçon)' },
  { id: 'v75', level: 3, topic: 'Famille', en: 'boyfriend', fr: 'petit ami' },

  // Niveau 4 — Nourriture
  { id: 'v18', level: 4, topic: 'Nourriture', en: 'water', fr: 'eau' },
  { id: 'v19', level: 4, topic: 'Nourriture', en: 'bread', fr: 'pain' },
  { id: 'v20', level: 4, topic: 'Nourriture', en: 'apple', fr: 'pomme' },
  { id: 'v21', level: 4, topic: 'Nourriture', en: 'chicken', fr: 'poulet' },
  { id: 'v22', level: 4, topic: 'Nourriture', en: 'cheese', fr: 'fromage' },
  { id: 'v23', level: 4, topic: 'Nourriture', en: 'egg', fr: 'œuf' },
  { id: 'v76', level: 4, topic: 'Nourriture', en: 'meat', fr: 'viande' },
  { id: 'v77', level: 4, topic: 'Nourriture', en: 'fish', fr: 'poisson' },
  { id: 'v78', level: 4, topic: 'Nourriture', en: 'rice', fr: 'riz' },
  { id: 'v79', level: 4, topic: 'Nourriture', en: 'milk', fr: 'lait' },
  { id: 'v80', level: 4, topic: 'Nourriture', en: 'sugar', fr: 'sucre' },
  { id: 'v81', level: 4, topic: 'Nourriture', en: 'salt', fr: 'sel' },
  { id: 'v82', level: 4, topic: 'Nourriture', en: 'coffee', fr: 'café (boisson)' },
  { id: 'v83', level: 4, topic: 'Nourriture', en: 'wine', fr: 'vin' },
  { id: 'v84', level: 4, topic: 'Nourriture', en: 'breakfast', fr: 'petit-déjeuner' },

  // Niveau 5 — Vie quotidienne
  { id: 'v24', level: 5, topic: 'Vie quotidienne', en: 'car', fr: 'voiture' },
  { id: 'v25', level: 5, topic: 'Vie quotidienne', en: 'computer', fr: 'ordinateur' },
  { id: 'v26', level: 5, topic: 'Vie quotidienne', en: 'mobile phone', fr: 'téléphone portable' },
  { id: 'v27', level: 5, topic: 'Vie quotidienne', en: 'juice', fr: 'jus' },
  { id: 'v28', level: 5, topic: 'Vie quotidienne', en: 'potato', fr: 'pomme de terre' },
  { id: 'v85', level: 5, topic: 'Vie quotidienne', en: 'house', fr: 'maison' },
  { id: 'v86', level: 5, topic: 'Vie quotidienne', en: 'bedroom', fr: 'chambre' },
  { id: 'v87', level: 5, topic: 'Vie quotidienne', en: 'kitchen', fr: 'cuisine (pièce)' },
  { id: 'v88', level: 5, topic: 'Vie quotidienne', en: 'bathroom', fr: 'salle de bain' },
  { id: 'v89', level: 5, topic: 'Vie quotidienne', en: 'window', fr: 'fenêtre' },
  { id: 'v90', level: 5, topic: 'Vie quotidienne', en: 'door', fr: 'porte' },
  { id: 'v91', level: 5, topic: 'Vie quotidienne', en: 'key', fr: 'clé' },
  { id: 'v92', level: 5, topic: 'Vie quotidienne', en: 'money', fr: 'argent' },
  { id: 'v93', level: 5, topic: 'Vie quotidienne', en: 'city', fr: 'ville' },

  // Niveau 6 — Travail
  { id: 'v29', level: 6, topic: 'Travail', en: 'work', fr: 'travail' },
  { id: 'v30', level: 6, topic: 'Travail', en: 'office', fr: 'bureau' },
  { id: 'v31', level: 6, topic: 'Travail', en: 'meeting', fr: 'réunion' },
  { id: 'v32', level: 6, topic: 'Travail', en: 'boss', fr: 'chef / patron' },
  { id: 'v33', level: 6, topic: 'Travail', en: 'employee', fr: 'employé' },
  { id: 'v94', level: 6, topic: 'Travail', en: 'school', fr: 'école' },
  { id: 'v95', level: 6, topic: 'Travail', en: 'university', fr: 'université' },
  { id: 'v96', level: 6, topic: 'Travail', en: 'teacher', fr: 'professeur' },
  { id: 'v97', level: 6, topic: 'Travail', en: 'student', fr: 'étudiant' },
  { id: 'v98', level: 6, topic: 'Travail', en: 'exam', fr: 'examen' },
  { id: 'v99', level: 6, topic: 'Travail', en: 'homework', fr: 'devoir' },
  { id: 'v100', level: 6, topic: 'Travail', en: 'schedule', fr: 'horaire' },
  { id: 'v101', level: 6, topic: 'Travail', en: 'salary', fr: 'salaire' },
  { id: 'v102', level: 6, topic: 'Travail', en: 'email', fr: 'email' },

  // Niveau 7 — Voyage
  { id: 'v34', level: 7, topic: 'Voyage', en: 'passport', fr: 'passeport' },
  { id: 'v35', level: 7, topic: 'Voyage', en: 'luggage', fr: 'bagage' },
  { id: 'v36', level: 7, topic: 'Voyage', en: 'flight', fr: 'vol (avion)' },
  { id: 'v37', level: 7, topic: 'Voyage', en: 'airport', fr: 'aéroport' },
  { id: 'v38', level: 7, topic: 'Voyage', en: 'ticket', fr: 'billet' },
  { id: 'v103', level: 7, topic: 'Voyage', en: 'train', fr: 'train' },
  { id: 'v104', level: 7, topic: 'Voyage', en: 'bus', fr: 'bus' },
  { id: 'v105', level: 7, topic: 'Voyage', en: 'station', fr: 'gare' },
  { id: 'v106', level: 7, topic: 'Voyage', en: 'reservation', fr: 'réservation' },
  { id: 'v107', level: 7, topic: 'Voyage', en: 'hotel', fr: 'hôtel' },
  { id: 'v108', level: 7, topic: 'Voyage', en: 'map', fr: 'carte (plan)' },
  { id: 'v109', level: 7, topic: 'Voyage', en: 'foreigner', fr: 'étranger' },
  { id: 'v110', level: 7, topic: 'Voyage', en: 'tourist', fr: 'touriste' },
  { id: 'v111', level: 7, topic: 'Voyage', en: 'delay', fr: 'retard' },

  // Niveau 8 — Connecteurs
  { id: 'v39', level: 8, topic: 'Connecteurs', en: 'although', fr: 'bien que / même si' },
  { id: 'v40', level: 8, topic: 'Connecteurs', en: 'however', fr: 'cependant' },
  { id: 'v41', level: 8, topic: 'Connecteurs', en: 'despite', fr: 'malgré' },
  { id: 'v42', level: 8, topic: 'Connecteurs', en: 'therefore', fr: 'par conséquent' },
  { id: 'v43', level: 8, topic: 'Connecteurs', en: 'in fact', fr: 'en fait' },
  { id: 'v112', level: 8, topic: 'Connecteurs', en: 'moreover', fr: 'de plus' },
  { id: 'v113', level: 8, topic: 'Connecteurs', en: 'while', fr: 'pendant que' },
  { id: 'v114', level: 8, topic: 'Connecteurs', en: 'that’s why', fr: 'c’est pourquoi' },
  { id: 'v115', level: 8, topic: 'Connecteurs', en: 'on the other hand', fr: 'en revanche' },
  { id: 'v116', level: 8, topic: 'Connecteurs', en: 'unless', fr: 'à moins que' },
  { id: 'v117', level: 8, topic: 'Connecteurs', en: 'as soon as', fr: 'dès que' },
  { id: 'v118', level: 8, topic: 'Connecteurs', en: 'given that', fr: 'étant donné que' },
  { id: 'v119', level: 8, topic: 'Connecteurs', en: 'nevertheless', fr: 'néanmoins' },
  { id: 'v120', level: 8, topic: 'Connecteurs', en: 'as soon as possible', fr: 'le plus tôt possible' },

  // Niveau 9 — Expressions idiomatiques
  { id: 'v44', level: 9, topic: 'Expressions', en: 'you’re welcome', fr: 'de rien / il n’y a pas de quoi' },
  { id: 'v45', level: 9, topic: 'Expressions', en: 'no way!', fr: 'allons donc ! / pas du tout !' },
  { id: 'v46', level: 9, topic: 'Expressions', en: 'to put one’s foot in it', fr: 'faire une gaffe' },
  { id: 'v47', level: 9, topic: 'Expressions', en: 'to be fed up', fr: 'en avoir marre' },
  { id: 'v48', level: 9, topic: 'Expressions', en: 'to be in a bad mood', fr: 'être de mauvaise humeur' },
  { id: 'v121', level: 9, topic: 'Expressions', en: 'to be annoying', fr: 'casser les pieds (embêter)' },
  { id: 'v122', level: 9, topic: 'Expressions', en: 'to cost an arm and a leg', fr: 'coûter les yeux de la tête' },
  { id: 'v123', level: 9, topic: 'Expressions', en: 'to be a piece of cake', fr: 'être du gâteau (facile)' },
  { id: 'v124', level: 9, topic: 'Expressions', en: 'to pull someone’s leg', fr: 'se moquer de quelqu’un' },
  { id: 'v125', level: 9, topic: 'Expressions', en: 'to have your head in the clouds', fr: 'être dans la lune' },
  { id: 'v126', level: 9, topic: 'Expressions', en: 'to not mince your words', fr: 'ne pas mâcher ses mots' },
  { id: 'v127', level: 9, topic: 'Expressions', en: 'to get your act together', fr: 'se motiver' },
  { id: 'v128', level: 9, topic: 'Expressions', en: 'to hit the nail on the head', fr: 'mettre dans le mille' },
  { id: 'v129', level: 9, topic: 'Expressions', en: 'to rain cats and dogs', fr: 'pleuvoir des cordes' },

  // Niveau 1 — Interactions courantes
  { id: 'v130', level: 1, topic: 'Interactions courantes', en: 'what’s your name?', fr: 'comment tu t’appelles ?' },
  { id: 'v131', level: 1, topic: 'Interactions courantes', en: 'where are you from?', fr: 'd’où viens-tu ?' },
  { id: 'v132', level: 1, topic: 'Interactions courantes', en: 'how old are you?', fr: 'quel âge as-tu ?' },
  { id: 'v133', level: 1, topic: 'Interactions courantes', en: 'where do you live?', fr: 'où habites-tu ?' },
  { id: 'v134', level: 1, topic: 'Interactions courantes', en: 'I don’t understand', fr: 'je ne comprends pas' },
  { id: 'v135', level: 1, topic: 'Interactions courantes', en: 'can you repeat that, please?', fr: 'pouvez-vous répéter, s’il vous plaît ?' },
  { id: 'v136', level: 1, topic: 'Interactions courantes', en: 'speak more slowly', fr: 'parlez plus lentement' },
  { id: 'v137', level: 1, topic: 'Interactions courantes', en: 'I don’t know', fr: 'je ne sais pas' },
  { id: 'v138', level: 1, topic: 'Interactions courantes', en: 'of course', fr: 'bien sûr' },
  { id: 'v139', level: 1, topic: 'Interactions courantes', en: 'maybe', fr: 'peut-être' },
  { id: 'v140', level: 1, topic: 'Interactions courantes', en: 'okay', fr: 'd’accord' },
  { id: 'v141', level: 1, topic: 'Interactions courantes', en: 'no problem', fr: 'pas de problème' },
  { id: 'v142', level: 1, topic: 'Interactions courantes', en: 'see you in a bit', fr: 'à tout à l’heure' },
  { id: 'v143', level: 1, topic: 'Interactions courantes', en: 'have a good day', fr: 'bonne journée' },
  { id: 'v144', level: 1, topic: 'Interactions courantes', en: 'good luck', fr: 'bonne chance' },
  { id: 'v145', level: 1, topic: 'Interactions courantes', en: 'congratulations', fr: 'félicitations' },
  { id: 'v146', level: 1, topic: 'Interactions courantes', en: 'happy birthday', fr: 'joyeux anniversaire' },
  { id: 'v147', level: 1, topic: 'Interactions courantes', en: 'cheers!', fr: 'santé ! (trinquer)' },
  { id: 'v148', level: 1, topic: 'Interactions courantes', en: 'how do you spell it?', fr: 'comment ça s’écrit ?' },
  { id: 'v149', level: 1, topic: 'Interactions courantes', en: 'I’m lost', fr: 'je suis perdu' },
  { id: 'v150', level: 1, topic: 'Interactions courantes', en: 'can you help me?', fr: 'pouvez-vous m’aider ?' },
  { id: 'v151', level: 1, topic: 'Interactions courantes', en: 'with pleasure', fr: 'avec plaisir' },
  { id: 'v152', level: 1, topic: 'Interactions courantes', en: 'it doesn’t matter', fr: 'ça ne fait rien' },
  { id: 'v153', level: 1, topic: 'Interactions courantes', en: 'what a shame', fr: 'quel dommage' },
  { id: 'v154', level: 1, topic: 'Interactions courantes', en: 'never mind', fr: 'tant pis' },
  { id: 'v155', level: 1, topic: 'Interactions courantes', en: 'sorry, I’m running late', fr: 'désolé, je suis en retard' },

  // Niveau 2 — Temps et calendrier
  { id: 'v156', level: 2, topic: 'Temps et calendrier', en: 'Monday', fr: 'lundi' },
  { id: 'v157', level: 2, topic: 'Temps et calendrier', en: 'Tuesday', fr: 'mardi' },
  { id: 'v158', level: 2, topic: 'Temps et calendrier', en: 'Wednesday', fr: 'mercredi' },
  { id: 'v159', level: 2, topic: 'Temps et calendrier', en: 'Thursday', fr: 'jeudi' },
  { id: 'v160', level: 2, topic: 'Temps et calendrier', en: 'Friday', fr: 'vendredi' },
  { id: 'v161', level: 2, topic: 'Temps et calendrier', en: 'Saturday', fr: 'samedi' },
  { id: 'v162', level: 2, topic: 'Temps et calendrier', en: 'Sunday', fr: 'dimanche' },
  { id: 'v163', level: 2, topic: 'Temps et calendrier', en: 'January', fr: 'janvier' },
  { id: 'v164', level: 2, topic: 'Temps et calendrier', en: 'February', fr: 'février' },
  { id: 'v165', level: 2, topic: 'Temps et calendrier', en: 'March', fr: 'mars' },
  { id: 'v166', level: 2, topic: 'Temps et calendrier', en: 'April', fr: 'avril' },
  { id: 'v167', level: 2, topic: 'Temps et calendrier', en: 'May', fr: 'mai' },
  { id: 'v168', level: 2, topic: 'Temps et calendrier', en: 'June', fr: 'juin' },
  { id: 'v169', level: 2, topic: 'Temps et calendrier', en: 'July', fr: 'juillet' },
  { id: 'v170', level: 2, topic: 'Temps et calendrier', en: 'August', fr: 'août' },
  { id: 'v171', level: 2, topic: 'Temps et calendrier', en: 'September', fr: 'septembre' },
  { id: 'v172', level: 2, topic: 'Temps et calendrier', en: 'October', fr: 'octobre' },
  { id: 'v173', level: 2, topic: 'Temps et calendrier', en: 'November', fr: 'novembre' },
  { id: 'v174', level: 2, topic: 'Temps et calendrier', en: 'December', fr: 'décembre' },
  { id: 'v175', level: 2, topic: 'Temps et calendrier', en: 'today', fr: 'aujourd’hui' },
  { id: 'v176', level: 2, topic: 'Temps et calendrier', en: 'tomorrow', fr: 'demain' },
  { id: 'v177', level: 2, topic: 'Temps et calendrier', en: 'yesterday', fr: 'hier' },
  { id: 'v178', level: 2, topic: 'Temps et calendrier', en: 'the week', fr: 'la semaine' },
  { id: 'v179', level: 2, topic: 'Temps et calendrier', en: 'the month', fr: 'le mois' },
  { id: 'v180', level: 2, topic: 'Temps et calendrier', en: 'the year', fr: 'l’année' },
  { id: 'v181', level: 2, topic: 'Temps et calendrier', en: 'the hour', fr: 'l’heure' },
  { id: 'v182', level: 2, topic: 'Temps et calendrier', en: 'the minute', fr: 'la minute' },
  { id: 'v183', level: 2, topic: 'Temps et calendrier', en: 'the morning', fr: 'le matin' },
  { id: 'v184', level: 2, topic: 'Temps et calendrier', en: 'the afternoon', fr: 'l’après-midi' },
  { id: 'v185', level: 2, topic: 'Temps et calendrier', en: 'the evening', fr: 'le soir' },
  { id: 'v186', level: 2, topic: 'Temps et calendrier', en: 'what time is it?', fr: 'quelle heure est-il ?' },
  { id: 'v187', level: 2, topic: 'Temps et calendrier', en: 'early', fr: 'tôt' },
  { id: 'v188', level: 2, topic: 'Temps et calendrier', en: 'on time', fr: 'à l’heure (ponctuel)' },

  // Niveau 3 — Corps et santé
  { id: 'v189', level: 3, topic: 'Corps et santé', en: 'the head', fr: 'la tête' },
  { id: 'v190', level: 3, topic: 'Corps et santé', en: 'the hair', fr: 'les cheveux' },
  { id: 'v191', level: 3, topic: 'Corps et santé', en: 'the eyes', fr: 'les yeux' },
  { id: 'v192', level: 3, topic: 'Corps et santé', en: 'the nose', fr: 'le nez' },
  { id: 'v193', level: 3, topic: 'Corps et santé', en: 'the mouth', fr: 'la bouche' },
  { id: 'v194', level: 3, topic: 'Corps et santé', en: 'the teeth', fr: 'les dents' },
  { id: 'v195', level: 3, topic: 'Corps et santé', en: 'the ear', fr: 'l’oreille' },
  { id: 'v196', level: 3, topic: 'Corps et santé', en: 'the neck', fr: 'le cou' },
  { id: 'v197', level: 3, topic: 'Corps et santé', en: 'the shoulder', fr: 'l’épaule' },
  { id: 'v198', level: 3, topic: 'Corps et santé', en: 'the arm', fr: 'le bras' },
  { id: 'v199', level: 3, topic: 'Corps et santé', en: 'the hand', fr: 'la main' },
  { id: 'v200', level: 3, topic: 'Corps et santé', en: 'the fingers', fr: 'les doigts' },
  { id: 'v201', level: 3, topic: 'Corps et santé', en: 'the back', fr: 'le dos' },
  { id: 'v202', level: 3, topic: 'Corps et santé', en: 'the leg', fr: 'la jambe' },
  { id: 'v203', level: 3, topic: 'Corps et santé', en: 'the foot', fr: 'le pied' },
  { id: 'v204', level: 3, topic: 'Corps et santé', en: 'the heart', fr: 'le cœur' },
  { id: 'v205', level: 3, topic: 'Corps et santé', en: 'the stomach', fr: 'l’estomac' },
  { id: 'v206', level: 3, topic: 'Corps et santé', en: 'sick', fr: 'malade' },
  { id: 'v207', level: 3, topic: 'Corps et santé', en: 'fever', fr: 'la fièvre' },
  { id: 'v208', level: 3, topic: 'Corps et santé', en: 'a cold (illness)', fr: 'le rhume' },
  { id: 'v209', level: 3, topic: 'Corps et santé', en: 'pain', fr: 'la douleur' },
  { id: 'v210', level: 3, topic: 'Corps et santé', en: 'the doctor', fr: 'le médecin' },
  { id: 'v211', level: 3, topic: 'Corps et santé', en: 'the hospital', fr: 'l’hôpital' },
  { id: 'v212', level: 3, topic: 'Corps et santé', en: 'the pharmacy', fr: 'la pharmacie' },
  { id: 'v213', level: 3, topic: 'Corps et santé', en: 'medicine', fr: 'le médicament' },
  { id: 'v214', level: 3, topic: 'Corps et santé', en: 'a prescription', fr: 'une ordonnance' },

  // Niveau 4 — Restaurant et boissons
  { id: 'v215', level: 4, topic: 'Restaurant et boissons', en: 'the menu', fr: 'la carte (menu)' },
  { id: 'v216', level: 4, topic: 'Restaurant et boissons', en: 'the bill', fr: 'l’addition' },
  { id: 'v217', level: 4, topic: 'Restaurant et boissons', en: 'to book a table', fr: 'réserver une table' },
  { id: 'v218', level: 4, topic: 'Restaurant et boissons', en: 'the waiter', fr: 'le serveur' },
  { id: 'v219', level: 4, topic: 'Restaurant et boissons', en: 'a table for two', fr: 'une table pour deux' },
  { id: 'v220', level: 4, topic: 'Restaurant et boissons', en: 'a glass', fr: 'un verre' },
  { id: 'v221', level: 4, topic: 'Restaurant et boissons', en: 'a bottle', fr: 'une bouteille' },
  { id: 'v222', level: 4, topic: 'Restaurant et boissons', en: 'lunch', fr: 'le déjeuner' },
  { id: 'v223', level: 4, topic: 'Restaurant et boissons', en: 'dinner', fr: 'le dîner' },
  { id: 'v224', level: 4, topic: 'Restaurant et boissons', en: 'dessert', fr: 'le dessert' },
  { id: 'v225', level: 4, topic: 'Restaurant et boissons', en: 'the starter', fr: 'l’entrée (plat)' },
  { id: 'v226', level: 4, topic: 'Restaurant et boissons', en: 'the main course', fr: 'le plat principal' },
  { id: 'v227', level: 4, topic: 'Restaurant et boissons', en: 'vegetarian', fr: 'végétarien' },
  { id: 'v228', level: 4, topic: 'Restaurant et boissons', en: 'gluten-free', fr: 'sans gluten' },
  { id: 'v229', level: 4, topic: 'Restaurant et boissons', en: 'sparkling water', fr: 'l’eau gazeuse' },
  { id: 'v230', level: 4, topic: 'Restaurant et boissons', en: 'still water', fr: 'l’eau plate' },
  { id: 'v231', level: 4, topic: 'Restaurant et boissons', en: 'beer', fr: 'la bière' },
  { id: 'v232', level: 4, topic: 'Restaurant et boissons', en: 'orange juice', fr: 'le jus d’orange' },
  { id: 'v233', level: 4, topic: 'Restaurant et boissons', en: 'to take away', fr: 'à emporter' },
  { id: 'v234', level: 4, topic: 'Restaurant et boissons', en: 'to eat in', fr: 'sur place' },
  { id: 'v235', level: 4, topic: 'Restaurant et boissons', en: 'delicious', fr: 'délicieux' },
  { id: 'v236', level: 4, topic: 'Restaurant et boissons', en: 'I’m hungry', fr: 'j’ai faim' },
  { id: 'v237', level: 4, topic: 'Restaurant et boissons', en: 'I’m thirsty', fr: 'j’ai soif' },
  { id: 'v238', level: 4, topic: 'Restaurant et boissons', en: 'the tip', fr: 'le pourboire' },

  // Niveau 5 — Logement et objets
  { id: 'v239', level: 5, topic: 'Logement et objets', en: 'the piece of furniture', fr: 'le meuble' },
  { id: 'v240', level: 5, topic: 'Logement et objets', en: 'the table', fr: 'la table' },
  { id: 'v241', level: 5, topic: 'Logement et objets', en: 'the chair', fr: 'la chaise' },
  { id: 'v242', level: 5, topic: 'Logement et objets', en: 'the bed', fr: 'le lit' },
  { id: 'v243', level: 5, topic: 'Logement et objets', en: 'the sofa', fr: 'le canapé' },
  { id: 'v244', level: 5, topic: 'Logement et objets', en: 'the wardrobe', fr: 'l’armoire' },
  { id: 'v245', level: 5, topic: 'Logement et objets', en: 'the shelf', fr: 'l’étagère' },
  { id: 'v246', level: 5, topic: 'Logement et objets', en: 'the lamp', fr: 'la lampe' },
  { id: 'v247', level: 5, topic: 'Logement et objets', en: 'the mirror', fr: 'le miroir' },
  { id: 'v248', level: 5, topic: 'Logement et objets', en: 'the fridge', fr: 'le réfrigérateur' },
  { id: 'v249', level: 5, topic: 'Logement et objets', en: 'the oven', fr: 'le four' },
  { id: 'v250', level: 5, topic: 'Logement et objets', en: 'the blanket', fr: 'la couverture' },
  { id: 'v251', level: 5, topic: 'Logement et objets', en: 'the washing machine', fr: 'le lave-linge' },
  { id: 'v252', level: 5, topic: 'Logement et objets', en: 'the vacuum cleaner', fr: 'l’aspirateur' },
  { id: 'v253', level: 5, topic: 'Logement et objets', en: 'the television', fr: 'la télévision' },
  { id: 'v254', level: 5, topic: 'Logement et objets', en: 'the balcony', fr: 'le balcon' },
  { id: 'v255', level: 5, topic: 'Logement et objets', en: 'the garden', fr: 'le jardin' },
  { id: 'v256', level: 5, topic: 'Logement et objets', en: 'the stairs', fr: 'l’escalier' },
  { id: 'v257', level: 5, topic: 'Logement et objets', en: 'the elevator', fr: 'l’ascenseur' },
  { id: 'v258', level: 5, topic: 'Logement et objets', en: 'the rent', fr: 'le loyer' },
  { id: 'v259', level: 5, topic: 'Logement et objets', en: 'the landlord', fr: 'le propriétaire' },
  { id: 'v260', level: 5, topic: 'Logement et objets', en: 'the neighbor', fr: 'le voisin' },
  { id: 'v261', level: 5, topic: 'Logement et objets', en: 'to tidy up', fr: 'ranger' },
  { id: 'v262', level: 5, topic: 'Logement et objets', en: 'to move (house)', fr: 'déménager' },

  // Niveau 6 — Achats et argent
  { id: 'v263', level: 6, topic: 'Achats et argent', en: 'the price', fr: 'le prix' },
  { id: 'v264', level: 6, topic: 'Achats et argent', en: 'expensive', fr: 'cher' },
  { id: 'v265', level: 6, topic: 'Achats et argent', en: 'cheap', fr: 'bon marché' },
  { id: 'v266', level: 6, topic: 'Achats et argent', en: 'the discount', fr: 'la réduction' },
  { id: 'v267', level: 6, topic: 'Achats et argent', en: 'the sales', fr: 'les soldes' },
  { id: 'v268', level: 6, topic: 'Achats et argent', en: 'the checkout', fr: 'la caisse' },
  { id: 'v269', level: 6, topic: 'Achats et argent', en: 'the debit/credit card', fr: 'la carte bancaire' },
  { id: 'v270', level: 6, topic: 'Achats et argent', en: 'cash', fr: 'l’espèce (argent liquide)' },
  { id: 'v271', level: 6, topic: 'Achats et argent', en: 'the receipt', fr: 'le reçu' },
  { id: 'v272', level: 6, topic: 'Achats et argent', en: 'the bag', fr: 'le sac' },
  { id: 'v273', level: 6, topic: 'Achats et argent', en: 'the size', fr: 'la taille' },
  { id: 'v274', level: 6, topic: 'Achats et argent', en: 'the color', fr: 'la couleur' },
  { id: 'v275', level: 6, topic: 'Achats et argent', en: 'to try on', fr: 'essayer (un vêtement)' },
  { id: 'v276', level: 6, topic: 'Achats et argent', en: 'to exchange', fr: 'échanger' },
  { id: 'v277', level: 6, topic: 'Achats et argent', en: 'to refund', fr: 'rembourser' },
  { id: 'v278', level: 6, topic: 'Achats et argent', en: 'the shopping mall', fr: 'le centre commercial' },
  { id: 'v279', level: 6, topic: 'Achats et argent', en: 'the market', fr: 'le marché' },
  { id: 'v280', level: 6, topic: 'Achats et argent', en: 'the shop', fr: 'la boutique' },
  { id: 'v281', level: 6, topic: 'Achats et argent', en: 'open', fr: 'ouvert' },
  { id: 'v282', level: 6, topic: 'Achats et argent', en: 'closed', fr: 'fermé' },
  { id: 'v283', level: 6, topic: 'Achats et argent', en: 'free (no cost)', fr: 'gratuit' },
  { id: 'v284', level: 6, topic: 'Achats et argent', en: 'to pay', fr: 'payer' },
  { id: 'v285', level: 6, topic: 'Achats et argent', en: 'how much does it cost?', fr: 'combien ça coûte ?' },
  { id: 'v286', level: 6, topic: 'Achats et argent', en: 'on sale', fr: 'en solde' },

  // Niveau 7 — Transports et directions
  { id: 'v287', level: 7, topic: 'Transports et directions', en: 'to the left', fr: 'à gauche' },
  { id: 'v288', level: 7, topic: 'Transports et directions', en: 'to the right', fr: 'à droite' },
  { id: 'v289', level: 7, topic: 'Transports et directions', en: 'straight ahead', fr: 'tout droit' },
  { id: 'v290', level: 7, topic: 'Transports et directions', en: 'to turn', fr: 'tourner' },
  { id: 'v291', level: 7, topic: 'Transports et directions', en: 'to cross', fr: 'traverser' },
  { id: 'v292', level: 7, topic: 'Transports et directions', en: 'the traffic light', fr: 'le feu rouge' },
  { id: 'v293', level: 7, topic: 'Transports et directions', en: 'the roundabout', fr: 'le rond-point' },
  { id: 'v294', level: 7, topic: 'Transports et directions', en: 'the sidewalk', fr: 'le trottoir' },
  { id: 'v295', level: 7, topic: 'Transports et directions', en: 'the subway', fr: 'le métro' },
  { id: 'v296', level: 7, topic: 'Transports et directions', en: 'the subway station', fr: 'la station de métro' },
  { id: 'v297', level: 7, topic: 'Transports et directions', en: 'the taxi', fr: 'le taxi' },
  { id: 'v298', level: 7, topic: 'Transports et directions', en: 'the bicycle', fr: 'le vélo' },
  { id: 'v299', level: 7, topic: 'Transports et directions', en: 'to drive', fr: 'conduire' },
  { id: 'v300', level: 7, topic: 'Transports et directions', en: 'to park', fr: 'se garer' },
  { id: 'v301', level: 7, topic: 'Transports et directions', en: 'the parking lot', fr: 'le parking' },
  { id: 'v302', level: 7, topic: 'Transports et directions', en: 'near', fr: 'près de' },
  { id: 'v303', level: 7, topic: 'Transports et directions', en: 'far from', fr: 'loin de' },
  { id: 'v304', level: 7, topic: 'Transports et directions', en: 'next to', fr: 'à côté de' },
  { id: 'v305', level: 7, topic: 'Transports et directions', en: 'opposite', fr: 'en face de' },
  { id: 'v306', level: 7, topic: 'Transports et directions', en: 'between', fr: 'entre' },
  { id: 'v307', level: 7, topic: 'Transports et directions', en: 'the exit', fr: 'la sortie' },
  { id: 'v308', level: 7, topic: 'Transports et directions', en: 'the entrance', fr: 'l’entrée (lieu)' },
  { id: 'v309', level: 7, topic: 'Transports et directions', en: 'to get lost', fr: 'se perdre' },
  { id: 'v310', level: 7, topic: 'Transports et directions', en: 'the passenger', fr: 'le passager' },

  // Niveau 8 — Adverbes de fréquence
  { id: 'v311', level: 8, topic: 'Adverbes de fréquence', en: 'often', fr: 'souvent' },
  { id: 'v312', level: 8, topic: 'Adverbes de fréquence', en: 'sometimes', fr: 'parfois' },
  { id: 'v313', level: 8, topic: 'Adverbes de fréquence', en: 'rarely', fr: 'rarement' },
  { id: 'v314', level: 8, topic: 'Adverbes de fréquence', en: 'never', fr: 'jamais' },
  { id: 'v315', level: 8, topic: 'Adverbes de fréquence', en: 'always', fr: 'toujours' },
  { id: 'v316', level: 8, topic: 'Adverbes de fréquence', en: 'already', fr: 'déjà' },
  { id: 'v317', level: 8, topic: 'Adverbes de fréquence', en: 'not yet', fr: 'pas encore' },
  { id: 'v318', level: 8, topic: 'Adverbes de fréquence', en: 'soon', fr: 'bientôt' },
  { id: 'v319', level: 8, topic: 'Adverbes de fréquence', en: 'right now', fr: 'tout de suite' },
  { id: 'v320', level: 8, topic: 'Adverbes de fréquence', en: 'finally', fr: 'enfin' },
  { id: 'v321', level: 8, topic: 'Adverbes de fréquence', en: 'first', fr: 'd’abord' },
  { id: 'v322', level: 8, topic: 'Adverbes de fréquence', en: 'then', fr: 'ensuite' },
  { id: 'v323', level: 8, topic: 'Adverbes de fréquence', en: 'next', fr: 'puis' },
  { id: 'v324', level: 8, topic: 'Adverbes de fréquence', en: 'at last', fr: 'finalement' },
  { id: 'v325', level: 8, topic: 'Adverbes de fréquence', en: 'again', fr: 'encore une fois' },
  { id: 'v326', level: 8, topic: 'Adverbes de fréquence', en: 'from time to time', fr: 'de temps en temps' },
  { id: 'v327', level: 8, topic: 'Adverbes de fréquence', en: 'every day', fr: 'chaque jour' },
  { id: 'v328', level: 8, topic: 'Adverbes de fréquence', en: 'every week', fr: 'chaque semaine' },
  { id: 'v329', level: 8, topic: 'Adverbes de fréquence', en: 'most of the time', fr: 'la plupart du temps' },
  { id: 'v330', level: 8, topic: 'Adverbes de fréquence', en: 'for a long time', fr: 'longtemps' },
  { id: 'v331', level: 8, topic: 'Adverbes de fréquence', en: 'recently', fr: 'récemment' },
  { id: 'v332', level: 8, topic: 'Adverbes de fréquence', en: 'coming soon', fr: 'prochainement' },

  // Niveau 9 — Émotions et opinions
  { id: 'v333', level: 9, topic: 'Émotions et opinions', en: 'happy', fr: 'content' },
  { id: 'v334', level: 9, topic: 'Émotions et opinions', en: 'sad', fr: 'triste' },
  { id: 'v335', level: 9, topic: 'Émotions et opinions', en: 'angry', fr: 'en colère' },
  { id: 'v336', level: 9, topic: 'Émotions et opinions', en: 'worried', fr: 'inquiet' },
  { id: 'v337', level: 9, topic: 'Émotions et opinions', en: 'tired', fr: 'fatigué' },
  { id: 'v338', level: 9, topic: 'Émotions et opinions', en: 'surprised', fr: 'surpris' },
  { id: 'v339', level: 9, topic: 'Émotions et opinions', en: 'proud', fr: 'fier' },
  { id: 'v340', level: 9, topic: 'Émotions et opinions', en: 'jealous', fr: 'jaloux' },
  { id: 'v341', level: 9, topic: 'Émotions et opinions', en: 'embarrassed', fr: 'gêné' },
  { id: 'v342', level: 9, topic: 'Émotions et opinions', en: 'relaxed', fr: 'détendu' },
  { id: 'v343', level: 9, topic: 'Émotions et opinions', en: 'stressed', fr: 'stressé' },
  { id: 'v344', level: 9, topic: 'Émotions et opinions', en: 'in love', fr: 'amoureux' },
  { id: 'v345', level: 9, topic: 'Émotions et opinions', en: 'I think that', fr: 'je pense que' },
  { id: 'v346', level: 9, topic: 'Émotions et opinions', en: 'in my opinion', fr: 'à mon avis' },
  { id: 'v347', level: 9, topic: 'Émotions et opinions', en: 'I agree', fr: 'je suis d’accord' },
  { id: 'v348', level: 9, topic: 'Émotions et opinions', en: 'I disagree', fr: 'je ne suis pas d’accord' },
  { id: 'v349', level: 9, topic: 'Émotions et opinions', en: 'I like it', fr: 'ça me plaît' },
  { id: 'v350', level: 9, topic: 'Émotions et opinions', en: 'I don’t like it', fr: 'ça ne me plaît pas' },
  { id: 'v351', level: 9, topic: 'Émotions et opinions', en: 'I love it', fr: 'j’adore' },
  { id: 'v352', level: 9, topic: 'Émotions et opinions', en: 'I hate it', fr: 'je déteste' },
  { id: 'v353', level: 9, topic: 'Émotions et opinions', en: 'I don’t mind', fr: 'ça m’est égal' },
  { id: 'v354', level: 9, topic: 'Émotions et opinions', en: 'without a doubt', fr: 'sans aucun doute' },
  { id: 'v355', level: 9, topic: 'Émotions et opinions', en: 'honestly', fr: 'honnêtement' },
  { id: 'v356', level: 9, topic: 'Émotions et opinions', en: 'frankly', fr: 'franchement' },
]

export function wordFor(card) {
  return card.en
}
