// Vocabulaire, organisé par niveau (1-9) et thème.
// `es` = forme commune aux deux variantes. `variant: { ES, LatAm }` = quand le mot diffère
// vraiment entre espagnol d'Espagne et d'Amérique Latine (sinon on garde juste `es`).
export const VOCAB = [
  // Niveau 1 — Salutations
  { id: 'v1', level: 1, topic: 'Salutations', es: 'hola', fr: 'salut / bonjour' },
  { id: 'v2', level: 1, topic: 'Salutations', es: 'buenos días', fr: 'bonjour (le matin)' },
  { id: 'v3', level: 1, topic: 'Salutations', es: 'buenas noches', fr: 'bonsoir / bonne nuit' },
  { id: 'v4', level: 1, topic: 'Salutations', es: 'gracias', fr: 'merci' },
  { id: 'v5', level: 1, topic: 'Salutations', es: 'por favor', fr: 's’il te/vous plaît' },
  { id: 'v6', level: 1, topic: 'Salutations', es: 'adiós', fr: 'au revoir' },
  { id: 'v49', level: 1, topic: 'Salutations', es: 'buenas tardes', fr: 'bon après-midi' },
  { id: 'v50', level: 1, topic: 'Salutations', es: 'hasta luego', fr: 'à plus tard' },
  { id: 'v51', level: 1, topic: 'Salutations', es: 'de nada', fr: 'de rien' },
  { id: 'v52', level: 1, topic: 'Salutations', es: 'perdón', fr: 'excusez-moi' },
  { id: 'v53', level: 1, topic: 'Salutations', es: 'lo siento', fr: 'je suis désolé' },
  { id: 'v54', level: 1, topic: 'Salutations', es: 'bienvenido', fr: 'bienvenue' },
  { id: 'v55', level: 1, topic: 'Salutations', es: '¿qué tal?', fr: 'comment ça va ? (familier)' },
  { id: 'v56', level: 1, topic: 'Salutations', es: 'encantado', fr: 'enchanté' },
  { id: 'v57', level: 1, topic: 'Salutations', es: 'buen provecho', fr: 'bon appétit' },

  // Niveau 2 — Bases
  { id: 'v7', level: 2, topic: 'Bases', es: 'uno', fr: 'un' },
  { id: 'v8', level: 2, topic: 'Bases', es: 'dos', fr: 'deux' },
  { id: 'v9', level: 2, topic: 'Bases', es: 'tres', fr: 'trois' },
  { id: 'v10', level: 2, topic: 'Bases', es: 'sí', fr: 'oui' },
  { id: 'v11', level: 2, topic: 'Bases', es: 'no', fr: 'non' },
  { id: 'v12', level: 2, topic: 'Bases', es: '¿cómo estás?', fr: 'comment vas-tu ?' },
  { id: 'v58', level: 2, topic: 'Bases', es: 'cuatro', fr: 'quatre' },
  { id: 'v59', level: 2, topic: 'Bases', es: 'cinco', fr: 'cinq' },
  { id: 'v60', level: 2, topic: 'Bases', es: 'seis', fr: 'six' },
  { id: 'v61', level: 2, topic: 'Bases', es: 'siete', fr: 'sept' },
  { id: 'v62', level: 2, topic: 'Bases', es: 'ocho', fr: 'huit' },
  { id: 'v63', level: 2, topic: 'Bases', es: 'nueve', fr: 'neuf' },
  { id: 'v64', level: 2, topic: 'Bases', es: 'diez', fr: 'dix' },
  { id: 'v65', level: 2, topic: 'Bases', es: 'también', fr: 'aussi' },
  { id: 'v66', level: 2, topic: 'Bases', es: 'ahora', fr: 'maintenant' },

  // Niveau 3 — Famille
  { id: 'v13', level: 3, topic: 'Famille', es: 'madre', fr: 'mère' },
  { id: 'v14', level: 3, topic: 'Famille', es: 'padre', fr: 'père' },
  { id: 'v15', level: 3, topic: 'Famille', es: 'hermana', fr: 'sœur' },
  { id: 'v16', level: 3, topic: 'Famille', es: 'hermano', fr: 'frère' },
  { id: 'v17', level: 3, topic: 'Famille', es: 'amigo', fr: 'ami' },
  { id: 'v67', level: 3, topic: 'Famille', es: 'hijo', fr: 'fils' },
  { id: 'v68', level: 3, topic: 'Famille', es: 'hija', fr: 'fille' },
  { id: 'v69', level: 3, topic: 'Famille', es: 'abuelo', fr: 'grand-père' },
  { id: 'v70', level: 3, topic: 'Famille', es: 'abuela', fr: 'grand-mère' },
  { id: 'v71', level: 3, topic: 'Famille', es: 'tío', fr: 'oncle' },
  { id: 'v72', level: 3, topic: 'Famille', es: 'tía', fr: 'tante' },
  { id: 'v73', level: 3, topic: 'Famille', es: 'primo', fr: 'cousin' },
  { id: 'v74', level: 3, topic: 'Famille', es: 'niño', fr: 'enfant (garçon)' },
  { id: 'v75', level: 3, topic: 'Famille', es: 'novio', fr: 'petit ami' },

  // Niveau 4 — Nourriture
  { id: 'v18', level: 4, topic: 'Nourriture', es: 'agua', fr: 'eau' },
  { id: 'v19', level: 4, topic: 'Nourriture', es: 'pan', fr: 'pain' },
  { id: 'v20', level: 4, topic: 'Nourriture', es: 'manzana', fr: 'pomme' },
  { id: 'v21', level: 4, topic: 'Nourriture', es: 'pollo', fr: 'poulet' },
  { id: 'v22', level: 4, topic: 'Nourriture', es: 'queso', fr: 'fromage' },
  { id: 'v23', level: 4, topic: 'Nourriture', es: 'huevo', fr: 'œuf' },
  { id: 'v76', level: 4, topic: 'Nourriture', es: 'carne', fr: 'viande' },
  { id: 'v77', level: 4, topic: 'Nourriture', es: 'pescado', fr: 'poisson' },
  { id: 'v78', level: 4, topic: 'Nourriture', es: 'arroz', fr: 'riz' },
  { id: 'v79', level: 4, topic: 'Nourriture', es: 'leche', fr: 'lait' },
  { id: 'v80', level: 4, topic: 'Nourriture', es: 'azúcar', fr: 'sucre' },
  { id: 'v81', level: 4, topic: 'Nourriture', es: 'sal', fr: 'sel' },
  { id: 'v82', level: 4, topic: 'Nourriture', es: 'café', fr: 'café (boisson)' },
  { id: 'v83', level: 4, topic: 'Nourriture', es: 'vino', fr: 'vin' },
  { id: 'v84', level: 4, topic: 'Nourriture', es: 'desayuno', fr: 'petit-déjeuner' },

  // Niveau 5 — Vie quotidienne (ici, les vraies différences Espagne / Amérique Latine)
  { id: 'v24', level: 5, topic: 'Vie quotidienne', variant: { ES: 'coche', LatAm: 'carro' }, fr: 'voiture' },
  { id: 'v25', level: 5, topic: 'Vie quotidienne', variant: { ES: 'ordenador', LatAm: 'computadora' }, fr: 'ordinateur' },
  { id: 'v26', level: 5, topic: 'Vie quotidienne', variant: { ES: 'móvil', LatAm: 'celular' }, fr: 'téléphone portable' },
  { id: 'v27', level: 5, topic: 'Vie quotidienne', variant: { ES: 'zumo', LatAm: 'jugo' }, fr: 'jus' },
  { id: 'v28', level: 5, topic: 'Vie quotidienne', variant: { ES: 'patata', LatAm: 'papa' }, fr: 'pomme de terre' },
  { id: 'v85', level: 5, topic: 'Vie quotidienne', es: 'casa', fr: 'maison' },
  { id: 'v86', level: 5, topic: 'Vie quotidienne', es: 'habitación', fr: 'chambre' },
  { id: 'v87', level: 5, topic: 'Vie quotidienne', es: 'cocina', fr: 'cuisine (pièce)' },
  { id: 'v88', level: 5, topic: 'Vie quotidienne', es: 'baño', fr: 'salle de bain' },
  { id: 'v89', level: 5, topic: 'Vie quotidienne', es: 'ventana', fr: 'fenêtre' },
  { id: 'v90', level: 5, topic: 'Vie quotidienne', es: 'puerta', fr: 'porte' },
  { id: 'v91', level: 5, topic: 'Vie quotidienne', es: 'llave', fr: 'clé' },
  { id: 'v92', level: 5, topic: 'Vie quotidienne', es: 'dinero', fr: 'argent' },
  { id: 'v93', level: 5, topic: 'Vie quotidienne', es: 'ciudad', fr: 'ville' },

  // Niveau 6 — Travail
  { id: 'v29', level: 6, topic: 'Travail', es: 'trabajo', fr: 'travail' },
  { id: 'v30', level: 6, topic: 'Travail', es: 'oficina', fr: 'bureau' },
  { id: 'v31', level: 6, topic: 'Travail', es: 'reunión', fr: 'réunion' },
  { id: 'v32', level: 6, topic: 'Travail', es: 'jefe', fr: 'chef / patron' },
  { id: 'v33', level: 6, topic: 'Travail', es: 'empleado', fr: 'employé' },
  { id: 'v94', level: 6, topic: 'Travail', es: 'escuela', fr: 'école' },
  { id: 'v95', level: 6, topic: 'Travail', es: 'universidad', fr: 'université' },
  { id: 'v96', level: 6, topic: 'Travail', es: 'profesor', fr: 'professeur' },
  { id: 'v97', level: 6, topic: 'Travail', es: 'estudiante', fr: 'étudiant' },
  { id: 'v98', level: 6, topic: 'Travail', es: 'examen', fr: 'examen' },
  { id: 'v99', level: 6, topic: 'Travail', es: 'tarea', fr: 'devoir' },
  { id: 'v100', level: 6, topic: 'Travail', es: 'horario', fr: 'horaire' },
  { id: 'v101', level: 6, topic: 'Travail', es: 'salario', fr: 'salaire' },
  { id: 'v102', level: 6, topic: 'Travail', es: 'correo electrónico', fr: 'email' },

  // Niveau 7 — Voyage
  { id: 'v34', level: 7, topic: 'Voyage', es: 'pasaporte', fr: 'passeport' },
  { id: 'v35', level: 7, topic: 'Voyage', es: 'equipaje', fr: 'bagage' },
  { id: 'v36', level: 7, topic: 'Voyage', es: 'vuelo', fr: 'vol (avion)' },
  { id: 'v37', level: 7, topic: 'Voyage', es: 'aeropuerto', fr: 'aéroport' },
  { id: 'v38', level: 7, topic: 'Voyage', variant: { ES: 'billete', LatAm: 'boleto' }, fr: 'billet' },
  { id: 'v103', level: 7, topic: 'Voyage', es: 'tren', fr: 'train' },
  { id: 'v104', level: 7, topic: 'Voyage', es: 'autobús', fr: 'bus' },
  { id: 'v105', level: 7, topic: 'Voyage', es: 'estación', fr: 'gare' },
  { id: 'v106', level: 7, topic: 'Voyage', es: 'reserva', fr: 'réservation' },
  { id: 'v107', level: 7, topic: 'Voyage', es: 'hotel', fr: 'hôtel' },
  { id: 'v108', level: 7, topic: 'Voyage', es: 'mapa', fr: 'carte (plan)' },
  { id: 'v109', level: 7, topic: 'Voyage', es: 'extranjero', fr: 'étranger' },
  { id: 'v110', level: 7, topic: 'Voyage', es: 'turista', fr: 'touriste' },
  { id: 'v111', level: 7, topic: 'Voyage', es: 'retraso', fr: 'retard' },

  // Niveau 8 — Connecteurs (expressions avancées)
  { id: 'v39', level: 8, topic: 'Connecteurs', es: 'aunque', fr: 'bien que / même si' },
  { id: 'v40', level: 8, topic: 'Connecteurs', es: 'sin embargo', fr: 'cependant' },
  { id: 'v41', level: 8, topic: 'Connecteurs', es: 'a pesar de', fr: 'malgré' },
  { id: 'v42', level: 8, topic: 'Connecteurs', es: 'por lo tanto', fr: 'par conséquent' },
  { id: 'v43', level: 8, topic: 'Connecteurs', es: 'de hecho', fr: 'en fait' },
  { id: 'v112', level: 8, topic: 'Connecteurs', es: 'además', fr: 'de plus' },
  { id: 'v113', level: 8, topic: 'Connecteurs', es: 'mientras', fr: 'pendant que' },
  { id: 'v114', level: 8, topic: 'Connecteurs', es: 'por eso', fr: 'c’est pourquoi' },
  { id: 'v115', level: 8, topic: 'Connecteurs', es: 'en cambio', fr: 'en revanche' },
  { id: 'v116', level: 8, topic: 'Connecteurs', es: 'a menos que', fr: 'à moins que' },
  { id: 'v117', level: 8, topic: 'Connecteurs', es: 'en cuanto', fr: 'dès que' },
  { id: 'v118', level: 8, topic: 'Connecteurs', es: 'puesto que', fr: 'étant donné que' },
  { id: 'v119', level: 8, topic: 'Connecteurs', es: 'no obstante', fr: 'néanmoins' },
  { id: 'v120', level: 8, topic: 'Connecteurs', es: 'cuanto antes', fr: 'le plus tôt possible' },

  // Niveau 9 — Expressions idiomatiques
  { id: 'v44', level: 9, topic: 'Expressions', es: 'no hay de qué', fr: 'de rien / il n’y a pas de quoi' },
  { id: 'v45', level: 9, topic: 'Expressions', es: '¡qué va!', fr: 'allons donc ! / pas du tout !' },
  { id: 'v46', level: 9, topic: 'Expressions', es: 'meter la pata', fr: 'faire une gaffe' },
  { id: 'v47', level: 9, topic: 'Expressions', es: 'estar hasta las narices', fr: 'en avoir marre' },
  { id: 'v48', level: 9, topic: 'Expressions', es: 'tener mala leche', fr: 'être de mauvaise humeur' },
  { id: 'v121', level: 9, topic: 'Expressions', es: 'dar la lata', fr: 'casser les pieds (embêter)' },
  { id: 'v122', level: 9, topic: 'Expressions', es: 'costar un ojo de la cara', fr: 'coûter les yeux de la tête' },
  { id: 'v123', level: 9, topic: 'Expressions', es: 'ser pan comido', fr: 'être du gâteau (facile)' },
  { id: 'v124', level: 9, topic: 'Expressions', es: 'tomar el pelo', fr: 'se moquer de quelqu’un' },
  { id: 'v125', level: 9, topic: 'Expressions', es: 'estar en las nubes', fr: 'être dans la lune' },
  { id: 'v126', level: 9, topic: 'Expressions', es: 'no tener pelos en la lengua', fr: 'ne pas mâcher ses mots' },
  { id: 'v127', level: 9, topic: 'Expressions', es: 'ponerse las pilas', fr: 'se motiver' },
  { id: 'v128', level: 9, topic: 'Expressions', es: 'dar en el clavo', fr: 'mettre dans le mille' },
  { id: 'v129', level: 9, topic: 'Expressions', es: 'llover a cántaros', fr: 'pleuvoir des cordes' },

  // Niveau 1 — Interactions courantes
  { id: 'v130', level: 1, topic: 'Interactions courantes', es: '¿cómo te llamas?', fr: 'comment tu t’appelles ?' },
  { id: 'v131', level: 1, topic: 'Interactions courantes', es: '¿de dónde eres?', fr: 'd’où viens-tu ?' },
  { id: 'v132', level: 1, topic: 'Interactions courantes', es: '¿cuántos años tienes?', fr: 'quel âge as-tu ?' },
  { id: 'v133', level: 1, topic: 'Interactions courantes', es: '¿dónde vives?', fr: 'où habites-tu ?' },
  { id: 'v134', level: 1, topic: 'Interactions courantes', es: 'no entiendo', fr: 'je ne comprends pas' },
  { id: 'v135', level: 1, topic: 'Interactions courantes', es: '¿puede repetir, por favor?', fr: 'pouvez-vous répéter, s’il vous plaît ?' },
  { id: 'v136', level: 1, topic: 'Interactions courantes', es: 'hable más despacio', fr: 'parlez plus lentement' },
  { id: 'v137', level: 1, topic: 'Interactions courantes', es: 'no lo sé', fr: 'je ne sais pas' },
  { id: 'v138', level: 1, topic: 'Interactions courantes', es: 'claro', fr: 'bien sûr' },
  { id: 'v139', level: 1, topic: 'Interactions courantes', es: 'quizás', fr: 'peut-être' },
  { id: 'v140', level: 1, topic: 'Interactions courantes', es: 'vale', fr: 'd’accord' },
  { id: 'v141', level: 1, topic: 'Interactions courantes', es: 'no hay problema', fr: 'pas de problème' },
  { id: 'v142', level: 1, topic: 'Interactions courantes', es: 'hasta ahora', fr: 'à tout à l’heure' },
  { id: 'v143', level: 1, topic: 'Interactions courantes', es: 'que tengas un buen día', fr: 'bonne journée' },
  { id: 'v144', level: 1, topic: 'Interactions courantes', es: 'buena suerte', fr: 'bonne chance' },
  { id: 'v145', level: 1, topic: 'Interactions courantes', es: 'felicidades', fr: 'félicitations' },
  { id: 'v146', level: 1, topic: 'Interactions courantes', es: 'feliz cumpleaños', fr: 'joyeux anniversaire' },
  { id: 'v147', level: 1, topic: 'Interactions courantes', es: '¡salud!', fr: 'santé ! (trinquer)' },
  { id: 'v148', level: 1, topic: 'Interactions courantes', es: '¿cómo se escribe?', fr: 'comment ça s’écrit ?' },
  { id: 'v149', level: 1, topic: 'Interactions courantes', es: 'estoy perdido', fr: 'je suis perdu' },
  { id: 'v150', level: 1, topic: 'Interactions courantes', es: '¿puede ayudarme?', fr: 'pouvez-vous m’aider ?' },
  { id: 'v151', level: 1, topic: 'Interactions courantes', es: 'con mucho gusto', fr: 'avec plaisir' },
  { id: 'v152', level: 1, topic: 'Interactions courantes', es: 'no pasa nada', fr: 'ça ne fait rien' },
  { id: 'v153', level: 1, topic: 'Interactions courantes', es: 'qué pena', fr: 'quel dommage' },
  { id: 'v154', level: 1, topic: 'Interactions courantes', es: 'da igual', fr: 'tant pis' },
  { id: 'v155', level: 1, topic: 'Interactions courantes', es: 'lo siento, llego tarde', fr: 'désolé, je suis en retard' },

  // Niveau 2 — Temps et calendrier
  { id: 'v156', level: 2, topic: 'Temps et calendrier', es: 'lunes', fr: 'lundi' },
  { id: 'v157', level: 2, topic: 'Temps et calendrier', es: 'martes', fr: 'mardi' },
  { id: 'v158', level: 2, topic: 'Temps et calendrier', es: 'miércoles', fr: 'mercredi' },
  { id: 'v159', level: 2, topic: 'Temps et calendrier', es: 'jueves', fr: 'jeudi' },
  { id: 'v160', level: 2, topic: 'Temps et calendrier', es: 'viernes', fr: 'vendredi' },
  { id: 'v161', level: 2, topic: 'Temps et calendrier', es: 'sábado', fr: 'samedi' },
  { id: 'v162', level: 2, topic: 'Temps et calendrier', es: 'domingo', fr: 'dimanche' },
  { id: 'v163', level: 2, topic: 'Temps et calendrier', es: 'enero', fr: 'janvier' },
  { id: 'v164', level: 2, topic: 'Temps et calendrier', es: 'febrero', fr: 'février' },
  { id: 'v165', level: 2, topic: 'Temps et calendrier', es: 'marzo', fr: 'mars' },
  { id: 'v166', level: 2, topic: 'Temps et calendrier', es: 'abril', fr: 'avril' },
  { id: 'v167', level: 2, topic: 'Temps et calendrier', es: 'mayo', fr: 'mai' },
  { id: 'v168', level: 2, topic: 'Temps et calendrier', es: 'junio', fr: 'juin' },
  { id: 'v169', level: 2, topic: 'Temps et calendrier', es: 'julio', fr: 'juillet' },
  { id: 'v170', level: 2, topic: 'Temps et calendrier', es: 'agosto', fr: 'août' },
  { id: 'v171', level: 2, topic: 'Temps et calendrier', es: 'septiembre', fr: 'septembre' },
  { id: 'v172', level: 2, topic: 'Temps et calendrier', es: 'octubre', fr: 'octobre' },
  { id: 'v173', level: 2, topic: 'Temps et calendrier', es: 'noviembre', fr: 'novembre' },
  { id: 'v174', level: 2, topic: 'Temps et calendrier', es: 'diciembre', fr: 'décembre' },
  { id: 'v175', level: 2, topic: 'Temps et calendrier', es: 'hoy', fr: 'aujourd’hui' },
  { id: 'v176', level: 2, topic: 'Temps et calendrier', es: 'mañana', fr: 'demain' },
  { id: 'v177', level: 2, topic: 'Temps et calendrier', es: 'ayer', fr: 'hier' },
  { id: 'v178', level: 2, topic: 'Temps et calendrier', es: 'la semana', fr: 'la semaine' },
  { id: 'v179', level: 2, topic: 'Temps et calendrier', es: 'el mes', fr: 'le mois' },
  { id: 'v180', level: 2, topic: 'Temps et calendrier', es: 'el año', fr: 'l’année' },
  { id: 'v181', level: 2, topic: 'Temps et calendrier', es: 'la hora', fr: 'l’heure' },
  { id: 'v182', level: 2, topic: 'Temps et calendrier', es: 'el minuto', fr: 'la minute' },
  { id: 'v183', level: 2, topic: 'Temps et calendrier', es: 'la mañana', fr: 'le matin' },
  { id: 'v184', level: 2, topic: 'Temps et calendrier', es: 'la tarde', fr: 'l’après-midi' },
  { id: 'v185', level: 2, topic: 'Temps et calendrier', es: 'la noche', fr: 'le soir' },
  { id: 'v186', level: 2, topic: 'Temps et calendrier', es: '¿qué hora es?', fr: 'quelle heure est-il ?' },
  { id: 'v187', level: 2, topic: 'Temps et calendrier', es: 'temprano', fr: 'tôt' },
  { id: 'v188', level: 2, topic: 'Temps et calendrier', es: 'a tiempo', fr: 'à l’heure (ponctuel)' },

  // Niveau 3 — Corps et santé
  { id: 'v189', level: 3, topic: 'Corps et santé', es: 'la cabeza', fr: 'la tête' },
  { id: 'v190', level: 3, topic: 'Corps et santé', es: 'el pelo', fr: 'les cheveux' },
  { id: 'v191', level: 3, topic: 'Corps et santé', es: 'los ojos', fr: 'les yeux' },
  { id: 'v192', level: 3, topic: 'Corps et santé', es: 'la nariz', fr: 'le nez' },
  { id: 'v193', level: 3, topic: 'Corps et santé', es: 'la boca', fr: 'la bouche' },
  { id: 'v194', level: 3, topic: 'Corps et santé', es: 'los dientes', fr: 'les dents' },
  { id: 'v195', level: 3, topic: 'Corps et santé', es: 'la oreja', fr: 'l’oreille' },
  { id: 'v196', level: 3, topic: 'Corps et santé', es: 'el cuello', fr: 'le cou' },
  { id: 'v197', level: 3, topic: 'Corps et santé', es: 'el hombro', fr: 'l’épaule' },
  { id: 'v198', level: 3, topic: 'Corps et santé', es: 'el brazo', fr: 'le bras' },
  { id: 'v199', level: 3, topic: 'Corps et santé', es: 'la mano', fr: 'la main' },
  { id: 'v200', level: 3, topic: 'Corps et santé', es: 'los dedos', fr: 'les doigts' },
  { id: 'v201', level: 3, topic: 'Corps et santé', es: 'la espalda', fr: 'le dos' },
  { id: 'v202', level: 3, topic: 'Corps et santé', es: 'la pierna', fr: 'la jambe' },
  { id: 'v203', level: 3, topic: 'Corps et santé', es: 'el pie', fr: 'le pied' },
  { id: 'v204', level: 3, topic: 'Corps et santé', es: 'el corazón', fr: 'le cœur' },
  { id: 'v205', level: 3, topic: 'Corps et santé', es: 'el estómago', fr: 'l’estomac' },
  { id: 'v206', level: 3, topic: 'Corps et santé', es: 'enfermo', fr: 'malade' },
  { id: 'v207', level: 3, topic: 'Corps et santé', es: 'la fiebre', fr: 'la fièvre' },
  { id: 'v208', level: 3, topic: 'Corps et santé', es: 'el resfriado', fr: 'le rhume' },
  { id: 'v209', level: 3, topic: 'Corps et santé', es: 'el dolor', fr: 'la douleur' },
  { id: 'v210', level: 3, topic: 'Corps et santé', es: 'el médico', fr: 'le médecin' },
  { id: 'v211', level: 3, topic: 'Corps et santé', es: 'el hospital', fr: 'l’hôpital' },
  { id: 'v212', level: 3, topic: 'Corps et santé', es: 'la farmacia', fr: 'la pharmacie' },
  { id: 'v213', level: 3, topic: 'Corps et santé', es: 'el medicamento', fr: 'le médicament' },
  { id: 'v214', level: 3, topic: 'Corps et santé', es: 'una receta', fr: 'une ordonnance' },

  // Niveau 4 — Restaurant et boissons
  { id: 'v215', level: 4, topic: 'Restaurant et boissons', es: 'la carta', fr: 'la carte (menu)' },
  { id: 'v216', level: 4, topic: 'Restaurant et boissons', es: 'la cuenta', fr: 'l’addition' },
  { id: 'v217', level: 4, topic: 'Restaurant et boissons', es: 'reservar una mesa', fr: 'réserver une table' },
  { id: 'v218', level: 4, topic: 'Restaurant et boissons', es: 'el camarero', fr: 'le serveur' },
  { id: 'v219', level: 4, topic: 'Restaurant et boissons', es: 'una mesa para dos', fr: 'une table pour deux' },
  { id: 'v220', level: 4, topic: 'Restaurant et boissons', es: 'un vaso', fr: 'un verre' },
  { id: 'v221', level: 4, topic: 'Restaurant et boissons', es: 'una botella', fr: 'une bouteille' },
  { id: 'v222', level: 4, topic: 'Restaurant et boissons', es: 'el almuerzo', fr: 'le déjeuner' },
  { id: 'v223', level: 4, topic: 'Restaurant et boissons', es: 'la cena', fr: 'le dîner' },
  { id: 'v224', level: 4, topic: 'Restaurant et boissons', es: 'el postre', fr: 'le dessert' },
  { id: 'v225', level: 4, topic: 'Restaurant et boissons', es: 'el entrante', fr: 'l’entrée (plat)' },
  { id: 'v226', level: 4, topic: 'Restaurant et boissons', es: 'el plato principal', fr: 'le plat principal' },
  { id: 'v227', level: 4, topic: 'Restaurant et boissons', es: 'vegetariano', fr: 'végétarien' },
  { id: 'v228', level: 4, topic: 'Restaurant et boissons', es: 'sin gluten', fr: 'sans gluten' },
  { id: 'v229', level: 4, topic: 'Restaurant et boissons', es: 'el agua con gas', fr: 'l’eau gazeuse' },
  { id: 'v230', level: 4, topic: 'Restaurant et boissons', es: 'el agua sin gas', fr: 'l’eau plate' },
  { id: 'v231', level: 4, topic: 'Restaurant et boissons', es: 'la cerveza', fr: 'la bière' },
  { id: 'v232', level: 4, topic: 'Restaurant et boissons', es: 'el zumo de naranja', fr: 'le jus d’orange' },
  { id: 'v233', level: 4, topic: 'Restaurant et boissons', es: 'para llevar', fr: 'à emporter' },
  { id: 'v234', level: 4, topic: 'Restaurant et boissons', es: 'para comer aquí', fr: 'sur place' },
  { id: 'v235', level: 4, topic: 'Restaurant et boissons', es: 'delicioso', fr: 'délicieux' },
  { id: 'v236', level: 4, topic: 'Restaurant et boissons', es: 'tengo hambre', fr: 'j’ai faim' },
  { id: 'v237', level: 4, topic: 'Restaurant et boissons', es: 'tengo sed', fr: 'j’ai soif' },
  { id: 'v238', level: 4, topic: 'Restaurant et boissons', es: 'la propina', fr: 'le pourboire' },

  // Niveau 5 — Logement et objets
  { id: 'v239', level: 5, topic: 'Logement et objets', es: 'el mueble', fr: 'le meuble' },
  { id: 'v240', level: 5, topic: 'Logement et objets', es: 'la mesa', fr: 'la table' },
  { id: 'v241', level: 5, topic: 'Logement et objets', es: 'la silla', fr: 'la chaise' },
  { id: 'v242', level: 5, topic: 'Logement et objets', es: 'la cama', fr: 'le lit' },
  { id: 'v243', level: 5, topic: 'Logement et objets', es: 'el sofá', fr: 'le canapé' },
  { id: 'v244', level: 5, topic: 'Logement et objets', es: 'el armario', fr: 'l’armoire' },
  { id: 'v245', level: 5, topic: 'Logement et objets', es: 'la estantería', fr: 'l’étagère' },
  { id: 'v246', level: 5, topic: 'Logement et objets', es: 'la lámpara', fr: 'la lampe' },
  { id: 'v247', level: 5, topic: 'Logement et objets', es: 'el espejo', fr: 'le miroir' },
  { id: 'v248', level: 5, topic: 'Logement et objets', es: 'el frigorífico', fr: 'le réfrigérateur' },
  { id: 'v249', level: 5, topic: 'Logement et objets', es: 'el horno', fr: 'le four' },
  { id: 'v250', level: 5, topic: 'Logement et objets', es: 'la manta', fr: 'la couverture' },
  { id: 'v251', level: 5, topic: 'Logement et objets', es: 'la lavadora', fr: 'le lave-linge' },
  { id: 'v252', level: 5, topic: 'Logement et objets', es: 'la aspiradora', fr: 'l’aspirateur' },
  { id: 'v253', level: 5, topic: 'Logement et objets', es: 'el televisor', fr: 'la télévision' },
  { id: 'v254', level: 5, topic: 'Logement et objets', es: 'el balcón', fr: 'le balcon' },
  { id: 'v255', level: 5, topic: 'Logement et objets', es: 'el jardín', fr: 'le jardin' },
  { id: 'v256', level: 5, topic: 'Logement et objets', es: 'la escalera', fr: 'l’escalier' },
  { id: 'v257', level: 5, topic: 'Logement et objets', es: 'el ascensor', fr: 'l’ascenseur' },
  { id: 'v258', level: 5, topic: 'Logement et objets', es: 'el alquiler', fr: 'le loyer' },
  { id: 'v259', level: 5, topic: 'Logement et objets', es: 'el propietario', fr: 'le propriétaire' },
  { id: 'v260', level: 5, topic: 'Logement et objets', es: 'el vecino', fr: 'le voisin' },
  { id: 'v261', level: 5, topic: 'Logement et objets', es: 'ordenar', fr: 'ranger' },
  { id: 'v262', level: 5, topic: 'Logement et objets', es: 'mudarse', fr: 'déménager' },

  // Niveau 6 — Achats et argent
  { id: 'v263', level: 6, topic: 'Achats et argent', es: 'el precio', fr: 'le prix' },
  { id: 'v264', level: 6, topic: 'Achats et argent', es: 'caro', fr: 'cher' },
  { id: 'v265', level: 6, topic: 'Achats et argent', es: 'barato', fr: 'bon marché' },
  { id: 'v266', level: 6, topic: 'Achats et argent', es: 'el descuento', fr: 'la réduction' },
  { id: 'v267', level: 6, topic: 'Achats et argent', es: 'las rebajas', fr: 'les soldes' },
  { id: 'v268', level: 6, topic: 'Achats et argent', es: 'la caja', fr: 'la caisse' },
  { id: 'v269', level: 6, topic: 'Achats et argent', es: 'la tarjeta bancaria', fr: 'la carte bancaire' },
  { id: 'v270', level: 6, topic: 'Achats et argent', es: 'el efectivo', fr: 'l’espèce (argent liquide)' },
  { id: 'v271', level: 6, topic: 'Achats et argent', es: 'el recibo', fr: 'le reçu' },
  { id: 'v272', level: 6, topic: 'Achats et argent', es: 'la bolsa', fr: 'le sac' },
  { id: 'v273', level: 6, topic: 'Achats et argent', es: 'la talla', fr: 'la taille' },
  { id: 'v274', level: 6, topic: 'Achats et argent', es: 'el color', fr: 'la couleur' },
  { id: 'v275', level: 6, topic: 'Achats et argent', es: 'probarse (algo)', fr: 'essayer (un vêtement)' },
  { id: 'v276', level: 6, topic: 'Achats et argent', es: 'cambiar', fr: 'échanger' },
  { id: 'v277', level: 6, topic: 'Achats et argent', es: 'reembolsar', fr: 'rembourser' },
  { id: 'v278', level: 6, topic: 'Achats et argent', es: 'el centro comercial', fr: 'le centre commercial' },
  { id: 'v279', level: 6, topic: 'Achats et argent', es: 'el mercado', fr: 'le marché' },
  { id: 'v280', level: 6, topic: 'Achats et argent', es: 'la tienda', fr: 'la boutique' },
  { id: 'v281', level: 6, topic: 'Achats et argent', es: 'abierto', fr: 'ouvert' },
  { id: 'v282', level: 6, topic: 'Achats et argent', es: 'cerrado', fr: 'fermé' },
  { id: 'v283', level: 6, topic: 'Achats et argent', es: 'gratis', fr: 'gratuit' },
  { id: 'v284', level: 6, topic: 'Achats et argent', es: 'pagar', fr: 'payer' },
  { id: 'v285', level: 6, topic: 'Achats et argent', es: '¿cuánto cuesta?', fr: 'combien ça coûte ?' },
  { id: 'v286', level: 6, topic: 'Achats et argent', es: 'de rebajas', fr: 'en solde' },

  // Niveau 7 — Transports et directions
  { id: 'v287', level: 7, topic: 'Transports et directions', es: 'a la izquierda', fr: 'à gauche' },
  { id: 'v288', level: 7, topic: 'Transports et directions', es: 'a la derecha', fr: 'à droite' },
  { id: 'v289', level: 7, topic: 'Transports et directions', es: 'todo recto', fr: 'tout droit' },
  { id: 'v290', level: 7, topic: 'Transports et directions', es: 'girar', fr: 'tourner' },
  { id: 'v291', level: 7, topic: 'Transports et directions', es: 'cruzar', fr: 'traverser' },
  { id: 'v292', level: 7, topic: 'Transports et directions', es: 'el semáforo', fr: 'le feu rouge' },
  { id: 'v293', level: 7, topic: 'Transports et directions', es: 'la rotonda', fr: 'le rond-point' },
  { id: 'v294', level: 7, topic: 'Transports et directions', es: 'la acera', fr: 'le trottoir' },
  { id: 'v295', level: 7, topic: 'Transports et directions', es: 'el metro', fr: 'le métro' },
  { id: 'v296', level: 7, topic: 'Transports et directions', es: 'la estación de metro', fr: 'la station de métro' },
  { id: 'v297', level: 7, topic: 'Transports et directions', es: 'el taxi', fr: 'le taxi' },
  { id: 'v298', level: 7, topic: 'Transports et directions', es: 'la bicicleta', fr: 'le vélo' },
  { id: 'v299', level: 7, topic: 'Transports et directions', es: 'conducir', fr: 'conduire' },
  { id: 'v300', level: 7, topic: 'Transports et directions', es: 'aparcar', fr: 'se garer' },
  { id: 'v301', level: 7, topic: 'Transports et directions', es: 'el aparcamiento', fr: 'le parking' },
  { id: 'v302', level: 7, topic: 'Transports et directions', es: 'cerca de', fr: 'près de' },
  { id: 'v303', level: 7, topic: 'Transports et directions', es: 'lejos de', fr: 'loin de' },
  { id: 'v304', level: 7, topic: 'Transports et directions', es: 'al lado de', fr: 'à côté de' },
  { id: 'v305', level: 7, topic: 'Transports et directions', es: 'enfrente de', fr: 'en face de' },
  { id: 'v306', level: 7, topic: 'Transports et directions', es: 'entre', fr: 'entre' },
  { id: 'v307', level: 7, topic: 'Transports et directions', es: 'la salida', fr: 'la sortie' },
  { id: 'v308', level: 7, topic: 'Transports et directions', es: 'la entrada', fr: 'l’entrée (lieu)' },
  { id: 'v309', level: 7, topic: 'Transports et directions', es: 'perderse', fr: 'se perdre' },
  { id: 'v310', level: 7, topic: 'Transports et directions', es: 'el pasajero', fr: 'le passager' },

  // Niveau 8 — Adverbes de fréquence
  { id: 'v311', level: 8, topic: 'Adverbes de fréquence', es: 'a menudo', fr: 'souvent' },
  { id: 'v312', level: 8, topic: 'Adverbes de fréquence', es: 'a veces', fr: 'parfois' },
  { id: 'v313', level: 8, topic: 'Adverbes de fréquence', es: 'rara vez', fr: 'rarement' },
  { id: 'v314', level: 8, topic: 'Adverbes de fréquence', es: 'nunca', fr: 'jamais' },
  { id: 'v315', level: 8, topic: 'Adverbes de fréquence', es: 'siempre', fr: 'toujours' },
  { id: 'v316', level: 8, topic: 'Adverbes de fréquence', es: 'ya', fr: 'déjà' },
  { id: 'v317', level: 8, topic: 'Adverbes de fréquence', es: 'todavía no', fr: 'pas encore' },
  { id: 'v318', level: 8, topic: 'Adverbes de fréquence', es: 'pronto', fr: 'bientôt' },
  { id: 'v319', level: 8, topic: 'Adverbes de fréquence', es: 'ahora mismo', fr: 'tout de suite' },
  { id: 'v320', level: 8, topic: 'Adverbes de fréquence', es: 'por fin', fr: 'enfin' },
  { id: 'v321', level: 8, topic: 'Adverbes de fréquence', es: 'primero', fr: 'd’abord' },
  { id: 'v322', level: 8, topic: 'Adverbes de fréquence', es: 'luego', fr: 'ensuite' },
  { id: 'v323', level: 8, topic: 'Adverbes de fréquence', es: 'después', fr: 'puis' },
  { id: 'v324', level: 8, topic: 'Adverbes de fréquence', es: 'finalmente', fr: 'finalement' },
  { id: 'v325', level: 8, topic: 'Adverbes de fréquence', es: 'otra vez', fr: 'encore une fois' },
  { id: 'v326', level: 8, topic: 'Adverbes de fréquence', es: 'de vez en cuando', fr: 'de temps en temps' },
  { id: 'v327', level: 8, topic: 'Adverbes de fréquence', es: 'cada día', fr: 'chaque jour' },
  { id: 'v328', level: 8, topic: 'Adverbes de fréquence', es: 'cada semana', fr: 'chaque semaine' },
  { id: 'v329', level: 8, topic: 'Adverbes de fréquence', es: 'la mayoría del tiempo', fr: 'la plupart du temps' },
  { id: 'v330', level: 8, topic: 'Adverbes de fréquence', es: 'mucho tiempo', fr: 'longtemps' },
  { id: 'v331', level: 8, topic: 'Adverbes de fréquence', es: 'recientemente', fr: 'récemment' },
  { id: 'v332', level: 8, topic: 'Adverbes de fréquence', es: 'próximamente', fr: 'prochainement' },

  // Niveau 9 — Émotions et opinions
  { id: 'v333', level: 9, topic: 'Émotions et opinions', es: 'contento', fr: 'content' },
  { id: 'v334', level: 9, topic: 'Émotions et opinions', es: 'triste', fr: 'triste' },
  { id: 'v335', level: 9, topic: 'Émotions et opinions', es: 'enfadado', fr: 'en colère' },
  { id: 'v336', level: 9, topic: 'Émotions et opinions', es: 'preocupado', fr: 'inquiet' },
  { id: 'v337', level: 9, topic: 'Émotions et opinions', es: 'cansado', fr: 'fatigué' },
  { id: 'v338', level: 9, topic: 'Émotions et opinions', es: 'sorprendido', fr: 'surpris' },
  { id: 'v339', level: 9, topic: 'Émotions et opinions', es: 'orgulloso', fr: 'fier' },
  { id: 'v340', level: 9, topic: 'Émotions et opinions', es: 'celoso', fr: 'jaloux' },
  { id: 'v341', level: 9, topic: 'Émotions et opinions', es: 'avergonzado', fr: 'gêné' },
  { id: 'v342', level: 9, topic: 'Émotions et opinions', es: 'relajado', fr: 'détendu' },
  { id: 'v343', level: 9, topic: 'Émotions et opinions', es: 'estresado', fr: 'stressé' },
  { id: 'v344', level: 9, topic: 'Émotions et opinions', es: 'enamorado', fr: 'amoureux' },
  { id: 'v345', level: 9, topic: 'Émotions et opinions', es: 'creo que', fr: 'je pense que' },
  { id: 'v346', level: 9, topic: 'Émotions et opinions', es: 'en mi opinión', fr: 'à mon avis' },
  { id: 'v347', level: 9, topic: 'Émotions et opinions', es: 'estoy de acuerdo', fr: 'je suis d’accord' },
  { id: 'v348', level: 9, topic: 'Émotions et opinions', es: 'no estoy de acuerdo', fr: 'je ne suis pas d’accord' },
  { id: 'v349', level: 9, topic: 'Émotions et opinions', es: 'me gusta', fr: 'ça me plaît' },
  { id: 'v350', level: 9, topic: 'Émotions et opinions', es: 'no me gusta', fr: 'ça ne me plaît pas' },
  { id: 'v351', level: 9, topic: 'Émotions et opinions', es: 'me encanta', fr: 'j’adore' },
  { id: 'v352', level: 9, topic: 'Émotions et opinions', es: 'odio', fr: 'je déteste' },
  { id: 'v353', level: 9, topic: 'Émotions et opinions', es: 'me da igual', fr: 'ça m’est égal' },
  { id: 'v354', level: 9, topic: 'Émotions et opinions', es: 'sin ninguna duda', fr: 'sans aucun doute' },
  { id: 'v355', level: 9, topic: 'Émotions et opinions', es: 'honestamente', fr: 'honnêtement' },
  { id: 'v356', level: 9, topic: 'Émotions et opinions', es: 'francamente', fr: 'franchement' },
]

// Retourne le mot espagnol adapté à la variante choisie par l'utilisateur ('ES' ou 'LatAm').
export function wordFor(card, variant) {
  if (card.variant) return card.variant[variant] || card.variant.ES
  return card.es
}
